name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Volta
        uses: volta-cli/action@v3

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
